### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Forbidden.

### ISSUE THREAD

**Issue by surakin** [Sorunome/mx-puppet-twitter#5]
I've set up everything as far as I can see, but I'm getting this error. (I set up a reverse proxy and pointed it to the internal host where the bridge is running, but I'm still getting this error.

Any tip about how can I debug it?

Thanks!
```
Jan-28 18:09:30.561 [Store] info: Starting DB Init
Jan-28 18:09:30.565 [Store] info: Filename present in config, using sqlite
Jan-28 18:09:30.566 [SQLite3] info: Opening database.db
Jan-28 18:09:30.570 [Store] info: Database schema version is 9, latest version is 9
(node:7454) UnhandledPromiseRejectionWarning: Error: Forbidden.
    at Request.request [as _callback] (/opt/mx-puppet-twitter/node_modules/twitter-webhooks/lib/helpers.js:27:33)
    at Request.self.callback (/opt/mx-puppet-twitter/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/opt/mx-puppet-twitter/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/opt/mx-puppet-twitter/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:7454) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7454) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by Sorunome** [comment]
Did you set up the reverse proxy correctly and have it unravel https?

**Comment by surakin** [comment]
Pretty sure I have (using apache) unless there's some special setting I'm missing.

**Comment by Sorunome** [comment]
Is the twitter block set up correctly in the config.yaml? In particular, is the `environment` block set up to what you set it in twitter?

**Comment by surakin** [comment]
I've set the same name in the dev environment label and the environment setting in config.yaml

**Comment by surakin** [comment]
I'm not familiar with what 'unravel https' means 🤔

**Comment by Sorunome** [comment]
apache/nginx/whatever needs to handle https requests and proxy them as http requests to the bridge, so you need a certificate and stuffs

**Comment by surakin** [comment]
Ah that, then yes, it should be correctly set up.

**Comment by surakin** [comment]
Any idea how can I print the failing https request?

**Comment by Sorunome** [comment]
Would you mind doing some code editing for debugging?

You see this in the traceback? `/opt/mx-puppet-twitter/node_modules/twitter-webhooks/lib/helpers.js:27:33`

When you look into that file that is

```
                    if (Array.isArray(json.errors)) {
                        error = new Error(json.errors[0].message);
                        error.code = json.errors[0].code;
                    } else {
                        error = new Error(response.statusMessage);
                        error.code = -1;
                    }
```

maybe just `console.log(json);` right before that if-condition?

**Comment by surakin** [comment]
{ errors: [ { code: 200, message: 'Forbidden.' } ] }

**Comment by Sorunome** [comment]
Well.....that sounds as if twitter doesn't allow you to set up a webhook somehow :I Ironically the code indicates success, so something is....off

**Comment by surakin** [comment]
Maybe I've set up the wrong environment? I see search tweets (30 days), search tweets (full archive) and account activity api

**Comment by surakin** [comment]
Actually, that was it :P I switched to account activity api and now it works

**Comment by Sorunome** [comment]
Great! Glad that was sorted out
