### ISSUE TITLE
Fix install instructions(?)

### ISSUE THREAD

**Issue by andrasdenes** [Sorunome/mx-puppet-twitter#6]
```node ./src``` - I am not too familiar with how node operates but executing a directory seems strange? and aslo does not work.

Then the closed issue where you referenced the discord puppet turned this up:
```npm run start -- -r [-c config.yaml] [-f discord-registration.yaml]``` 
This actually works, and generates the registration config.
(square brackets being optional and default values so just delete them in case you don't want to specify anything new.)

Maybe update the readme?. 
Not sure tho. As I said, I do not really know node so the first option might eventually work.

**Comment by cvincent** [comment]
Ah, looking at `docker-run.sh` it should point at `./src/index.js`. My mistake, locally I only run this as a Docker container.
